# Code Generated by Sidekick is for learning and experimentation purposes only.

variable "location" {
  description = "The Azure region to deploy resources in."
  type        = string
  default     = "eastus"
}

variable "resource_group_name" {
  description = "Name of the resource group."
  type        = string
}

variable "apim" {
  description = "APIM configuration block."
  type = object({
    name           = string
    publisher_name = string
    publisher_email = string
    sku_name       = string
    sku_capacity   = number
    virtual_network_type = string
    enable_managed_identity = bool
  })
}

variable "vnet" {
  description = "Virtual network configuration."
  type = object({
    name              = string
    address_space     = list(string)
    subnet_name       = string
    subnet_prefix     = string
    subnet_delegation = bool
  })
}

variable "key_vault" {
  description = "Key Vault integration settings."
  type = object({
    name                  = string
    secret_names          = list(string)
    enable_apim_access    = bool
  })
  default = {
    name               = ""
    secret_names       = []
    enable_apim_access = false
  }
}

variable "application_insights" {
  description = "Application Insights configuration."
  type = object({
    enabled = bool
    name    = string
  })
  default = {
    enabled = true
    name    = ""
  }
}

variable "tags" {
  description = "A map of tags to add to all resources."
  type        = map(string)
  default     = {
    environment = "dev"
    owner       = "apim-team"
    costcenter  = "12345"
  }
}

variable "additional_locations" {
  description = "List of additional locations for multi-region APIM."
  type = list(object({
    location      = string
    sku_name      = string
    sku_capacity  = number
    zone_redundant = bool
  }))
  default = []
}

variable "api_list" {
  description = "List of APIs to deploy to APIM."
  type = list(object({
    name        = string
    display_name = string
    path        = string
    protocols   = list(string)
    import_url  = string
  }))
  default = []
}

variable "named_values" {
  description = "List of named values (secrets or config) for APIM."
  type = list(object({
    name         = string
    display_name = string
    value        = string
    secret       = bool
    key_vault_id = string
  }))
  default = []
}
